// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"
	"time"

	"github.com/nutcas3/payment-rails/momo/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheStore creates a new instance of MockCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheStore {
	mock := &MockCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheStore is an autogenerated mock type for the CacheStore type
type MockCacheStore struct {
	mock.Mock
}

type MockCacheStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheStore) EXPECT() *MockCacheStore_Expecter {
	return &MockCacheStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCacheStore
func (_mock *MockCacheStore) Get(s string) (any, bool) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (any, bool)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCacheStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *MockCacheStore_Expecter) Get(s interface{}) *MockCacheStore_Get_Call {
	return &MockCacheStore_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *MockCacheStore_Get_Call) Run(run func(s string)) *MockCacheStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCacheStore_Get_Call) Return(v any, b bool) *MockCacheStore_Get_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *MockCacheStore_Get_Call) RunAndReturn(run func(s string) (any, bool)) *MockCacheStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCacheStore
func (_mock *MockCacheStore) Set(s string, v any, duration time.Duration) {
	_mock.Called(s, v, duration)
	return
}

// MockCacheStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - s string
//   - v any
//   - duration time.Duration
func (_e *MockCacheStore_Expecter) Set(s interface{}, v interface{}, duration interface{}) *MockCacheStore_Set_Call {
	return &MockCacheStore_Set_Call{Call: _e.mock.On("Set", s, v, duration)}
}

func (_c *MockCacheStore_Set_Call) Run(run func(s string, v any, duration time.Duration)) *MockCacheStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCacheStore_Set_Call) Return() *MockCacheStore_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheStore_Set_Call) RunAndReturn(run func(s string, v any, duration time.Duration)) *MockCacheStore_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// Call provides a mock function for the type MockBackend
func (_mock *MockBackend) Call(ctx context.Context, method string, path string, headers http.Header, params *common.Params, body any, result any) error {
	ret := _mock.Called(ctx, method, path, headers, params, body, result)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, http.Header, *common.Params, any, any) error); ok {
		r0 = returnFunc(ctx, method, path, headers, params, body, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockBackend_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - headers http.Header
//   - params *common.Params
//   - body any
//   - result any
func (_e *MockBackend_Expecter) Call(ctx interface{}, method interface{}, path interface{}, headers interface{}, params interface{}, body interface{}, result interface{}) *MockBackend_Call_Call {
	return &MockBackend_Call_Call{Call: _e.mock.On("Call", ctx, method, path, headers, params, body, result)}
}

func (_c *MockBackend_Call_Call) Run(run func(ctx context.Context, method string, path string, headers http.Header, params *common.Params, body any, result any)) *MockBackend_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 http.Header
		if args[3] != nil {
			arg3 = args[3].(http.Header)
		}
		var arg4 *common.Params
		if args[4] != nil {
			arg4 = args[4].(*common.Params)
		}
		var arg5 any
		if args[5] != nil {
			arg5 = args[5].(any)
		}
		var arg6 any
		if args[6] != nil {
			arg6 = args[6].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockBackend_Call_Call) Return(err error) *MockBackend_Call_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_Call_Call) RunAndReturn(run func(ctx context.Context, method string, path string, headers http.Header, params *common.Params, body any, result any) error) *MockBackend_Call_Call {
	_c.Call.Return(run)
	return _c
}
